import { json, mysqlTable, text, timestamp, varchar } from "drizzle-orm/mysql-core";

export const siteContent = mysqlTable("site_content", {
  id: varchar("id", { length: 64 }).primaryKey().notNull(),
  name: varchar("name", { length: 191 }).notNull(),
  title: varchar("title", { length: 191 }).notNull(),
  email: varchar("email", { length: 191 }).notNull(),
  location: varchar("location", { length: 191 }).notNull(),
  timezone: varchar("timezone", { length: 64 }).notNull(),
  socials: json("socials").notNull(),
  description: json("description").notNull(),
  availability: json("availability").notNull(),
  footerCopy: json("footerCopy").notNull(),
  ctaLabel: json("ctaLabel").notNull(),
  mobileEyebrow: json("mobileEyebrow").notNull(),
  mobileCta: json("mobileCta").notNull(),
  homeEyebrow: json("homeEyebrow").notNull(),
  homeHeroTitle: json("homeHeroTitle").notNull(),
  homeHeroBody: json("homeHeroBody").notNull(),
  homePrimaryCta: json("homePrimaryCta").notNull(),
  homeSecondaryCta: json("homeSecondaryCta").notNull(),
  homeHeroNoteTitle: json("homeHeroNoteTitle").notNull(),
  homeHeroNoteBody: json("homeHeroNoteBody").notNull(),
  contactEyebrow: json("contactEyebrow").notNull(),
  contactHeading: json("contactHeading").notNull(),
  contactBody: json("contactBody").notNull(),
  updatedAt: timestamp("updatedAt", { fsp: 3 }).notNull(),
  createdAt: timestamp("createdAt", { fsp: 3 }).notNull(),
});

export const aboutContent = mysqlTable("about_content", {
  id: varchar("id", { length: 64 }).primaryKey().notNull(),
  eyebrow: json("eyebrow").notNull(),
  heroTitle: json("heroTitle").notNull(),
  heroBody: json("heroBody").notNull(),
  storyEyebrow: json("storyEyebrow").notNull(),
  storyTitle: json("storyTitle").notNull(),
  story: json("story").notNull(),
  quote: json("quote").notNull(),
  quoteBy: json("quoteBy").notNull(),
  skillsEyebrow: json("skillsEyebrow").notNull(),
  skillsTitle: json("skillsTitle").notNull(),
  skills: json("skills").notNull(),
  updatedAt: timestamp("updatedAt", { fsp: 3 }).notNull(),
  createdAt: timestamp("createdAt", { fsp: 3 }).notNull(),
});
